FAST_CHAT_MODEL = "qwen3.6-flash"
FALLBACK_OR_RAG_MODEL = "deepseek-v4-flash"

FAST_CHAT_TIMEOUT_SECONDS = 15
FALLBACK_OR_RAG_TIMEOUT_SECONDS = 30

FAST_CHAT_MAX_TOKENS = 220
FALLBACK_OR_RAG_MAX_TOKENS = 700

